import JSZip from 'jszip';
import './styles.css';

const GOOD_TEAMS = new Set(['townsfolk', 'outsider', '镇民', '外来者']);
const EVIL_TEAMS = new Set(['minion', 'demon', '爪牙', '恶魔']);
const CORE_TEAMS = new Set([...GOOD_TEAMS, ...EVIL_TEAMS]);
const TEAM_LABELS = {
  zh: { townsfolk: '镇民', outsider: '外来者', minion: '爪牙', demon: '恶魔', traveler: '旅行者', fabled: '传奇角色', other: '其他' },
  en: { townsfolk: 'Townsfolk', outsider: 'Outsider', minion: 'Minion', demon: 'Demon', traveler: 'Traveler', fabled: 'Fabled', other: 'Other' }
};
const BACKGROUND_PRESETS = {
  'preset-parchment': '/backgrounds/RonpONN.png',
  'preset-frame': '/backgrounds/RonpONN2.png'
};

const UI_TEXT = {
  '载入示例': 'Load demo', '下载全部': 'Download all',
  'JSON 留在你的浏览器中。上传、微调、预览，然后带走一整套高清 Token。': 'Your JSON stays in your browser. Upload, fine-tune, preview, and download a complete set of high-resolution tokens.',
  '拖入剧本 JSON': 'Drop script JSON files', '或点击选择文件 · 支持多选与自动去重': 'or click to browse · multiple files and automatic deduplication supported',
  '选择文件': 'Choose files', '本地解析': 'Local processing', '无需注册': 'No sign-up', '高清 PNG': 'High-res PNG', '批量 ZIP': 'Batch ZIP',
  '作者：': 'Author:', '说书人Saber': 'Storyteller Saber', '项目已在': 'Open-source on', '，欢迎大家使用、提出建议和参与改进。': '. Everyone is welcome to use it, suggest ideas, and contribute.',
  'Token 设置': 'Token settings', '尺寸与画布': 'Size & canvas', '直径（英寸）': 'Diameter (inches)', '分辨率（DPI）': 'Resolution (DPI)', '画布留白': 'Canvas padding',
  '角色图像': 'Role image', '图像尺寸': 'Image size', '垂直位置': 'Vertical position', '背景': 'Background', '透明': 'Transparent', '纯色': 'Solid color',
  '内置 · 羊皮纸纹章': 'Built-in · Parchment crest', '内置 · 圆形边框': 'Built-in · Circular border', '自定义图片': 'Custom image',
  '内置背景': 'Built-in backgrounds', '点击即可使用': 'Click to apply', '羊皮纸纹章': 'Parchment crest', '圆形边框': 'Circular border', '背景颜色': 'Background color', '上传背景图': 'Upload background',
  '角色名称': 'Role name', '水平': 'Straight', '弧形': 'Curved', '字号': 'Font size', '文字高度': 'Text position', '弧形半径': 'Curve radius', '描边宽度': 'Stroke width', '自定义字体': 'Custom font', '选择': 'Choose',
  '辅助线与筛选': 'Guides & filtering', '显示裁切线': 'Show cut guide', '导出的 PNG 也会包含': 'Included in exported PNGs', '裁切线内缩': 'Guide inset',
  '仅保留四大角色类型': 'Core four role types only', '镇民、外来者、爪牙、恶魔': 'Townsfolk, Outsider, Minion, Demon', '＋ 添加更多 JSON': '+ Add more JSON',
  '未命名剧本': 'Untitled script', '枚 Token ·': 'tokens ·', '当前筛选下没有可生成的角色。': 'No roles match the current filter.',
  '单枚微调': 'Token adjustments', '阵营': 'Team', '图像地址': 'Image URL', '用本地图片替换': 'Replace with local image', '下载这枚 Token': 'Download this token',
  '镇民': 'Townsfolk', '外来者': 'Outsider', '爪牙': 'Minion', '恶魔': 'Demon', '旅行者': 'Traveler', '传奇角色': 'Fabled', '其他': 'Other'
};

const MESSAGES = {
  zh: {
    downloadAll: '下载全部', invalidRoot: '{file}：顶层必须是角色数组', noRoles: '没有找到可用角色', filesFailed: '{count} 个文件未能读取：{details}',
    unnamed: '未命名剧本', previewAlt: '{name} Token 预览', edit: '编辑', download: '下载', imageFailed: '图片加载失败',
    generatingOne: '正在生成「{name}」…', pngReady: 'PNG 已生成', generationFailed: '生成失败', progress: '生成 {current}/{total}', archiveReady: '整套 Token 已打包', batchFailed: '批量生成失败',
    fontReady: '已载入字体：{name}', fontFailed: '字体载入失败', reset: '已恢复默认参数', readme: '由 BOTC TokenMaker 生成\n剧本：{title}\nToken：{count} 枚\n画布：{size} × {size} px\n'
  },
  en: {
    downloadAll: 'Download all', invalidRoot: '{file}: the top level must be an array of roles', noRoles: 'No usable roles were found', filesFailed: '{count} file(s) could not be read: {details}',
    unnamed: 'Untitled script', previewAlt: '{name} token preview', edit: 'Edit', download: 'Download', imageFailed: 'Image failed to load',
    generatingOne: 'Generating “{name}”…', pngReady: 'PNG generated', generationFailed: 'Generation failed', progress: 'Generating {current}/{total}', archiveReady: 'Token set packaged', batchFailed: 'Batch generation failed',
    fontReady: 'Font loaded: {name}', fontFailed: 'Font failed to load', reset: 'Default settings restored', readme: 'Generated by BOTC TokenMaker\nScript: {title}\nTokens: {count}\nCanvas: {size} × {size} px\n'
  }
};

const defaults = {
  diameter: 1, dpi: 350, padding: 0, imageScale: .8, imageOffset: -.05,
  backgroundType: 'transparent', backgroundColor: '#f0eadc', backgroundImage: null,
  layout: 'line', fontSize: 37, textY: .8, curveRadius: .38, strokeWidth: 2,
  showGuide: false, guidePadding: 27, strictMode: true, fontFamily: 'TokenSerif'
};

const state = { settings: { ...defaults }, tokens: [], sourceTokens: [], title: '', currentToken: null, imageCache: new Map(), renderVersion: 0, lang: localStorage.getItem('botc-language') === 'en' ? 'en' : 'zh' };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const staticTextNodes = [];

function t(key, values = {}) {
  let value = MESSAGES[state.lang]?.[key] || MESSAGES.zh[key] || key;
  Object.entries(values).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); });
  return value;
}

function captureStaticTranslations() {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    const key = node.nodeValue.trim();
    if (!UI_TEXT[key]) continue;
    staticTextNodes.push({ node, key, leading: node.nodeValue.match(/^\s*/)?.[0] || '', trailing: node.nodeValue.match(/\s*$/)?.[0] || '' });
  }
}

function applyLanguage() {
  document.documentElement.lang = state.lang === 'en' ? 'en' : 'zh-CN';
  const english = state.lang === 'en';
  staticTextNodes.forEach(({ node, key, leading, trailing }) => {
    if (node.isConnected) node.nodeValue = `${leading}${english ? UI_TEXT[key] : key}${trailing}`;
  });
  $('#langToggleBtn').textContent = english ? '中文' : 'EN';
  $('#langToggleBtn').setAttribute('aria-label', english ? '切换到中文' : 'Switch to English');
  $('.brand').setAttribute('aria-label', english ? 'Back to home' : '返回首页');
  refs.dropzone.setAttribute('aria-label', english ? 'Choose or drop JSON files' : '选择或拖入 JSON 文件');
  $('meta[name="description"]').content = english ? 'Turn Blood on the Clocktower script JSON into print-ready role tokens in your browser.' : '在浏览器中把《血染钟楼》剧本 JSON 转换为可打印的角色 Token。';
  $('.segmented').setAttribute('aria-label', english ? 'Text layout' : '文字排列');
  $('#drawerBackdrop').setAttribute('aria-label', english ? 'Close editor' : '关闭编辑器');
  $('#resetBtn').title = english ? 'Restore default settings' : '恢复默认设置';
  $('[data-view="grid"]').title = english ? 'Grid view' : '网格视图';
  $('[data-view="list"]').title = english ? 'List view' : '列表视图';
  $('#closeDrawer').title = english ? 'Close editor' : '关闭编辑器';
  $('.background-presets [data-background="preset-parchment"]').title = english ? 'Use parchment crest background' : '使用羊皮纸纹章背景';
  $('.background-presets [data-background="preset-frame"]').title = english ? 'Use circular border background' : '使用圆形边框背景';
  refs.downloadAll.querySelector('span').textContent = t('downloadAll');
  refs.empty.textContent = english ? UI_TEXT['当前筛选下没有可生成的角色。'] : '当前筛选下没有可生成的角色。';
}

function teamLabel(team) { return TEAM_LABELS[state.lang][team] || team; }

const refs = {
  hero: $('#hero'), workspace: $('#workspace'), dropzone: $('#dropzone'), jsonInput: $('#jsonInput'),
  grid: $('#tokenGrid'), count: $('#tokenCount'), canvasInfo: $('#canvasInfo'), title: $('#scriptTitle'),
  notice: $('#notice'), empty: $('#emptyFilter'), downloadAll: $('#downloadAllBtn'), drawer: $('#editorDrawer'),
  editorCanvas: $('#editorCanvas'), toast: $('#toast')
};

const controls = {
  diameter: $('#diameter'), dpi: $('#dpi'), padding: $('#padding'), imageScale: $('#imageScale'),
  imageOffset: $('#imageOffset'), backgroundType: $('#backgroundType'), backgroundColor: $('#backgroundColor'),
  fontSize: $('#fontSize'), textY: $('#textY'), curveRadius: $('#curveRadius'), strokeWidth: $('#strokeWidth'),
  showGuide: $('#showGuide'), guidePadding: $('#guidePadding'), strictMode: $('#strictMode')
};

const demo = [
  { id: 'washerwoman', name: '洗衣妇', nameEn: 'Washerwoman', team: 'townsfolk', image: 'https://oss.gstonegames.com/data_file/clocktower/web/icons/washerwoman.png' },
  { id: 'fortune_teller', name: '占卜师', nameEn: 'Fortune Teller', team: 'townsfolk', image: 'https://oss.gstonegames.com/data_file/clocktower/web/icons/fortune_teller.png' },
  { id: 'witch', name: '女巫', nameEn: 'Witch', team: 'minion', image: 'https://oss.gstonegames.com/data_file/clocktower/web/icons/witch.png' },
  { id: 'po', name: '珀', nameEn: 'Po', team: 'demon', image: 'https://oss.gstonegames.com/data_file/clocktower/web/icons/po.png' }
];

function normalizeTeam(value = '') {
  const raw = String(value ?? '').trim();
  const team = raw.toLowerCase();
  return ({ 镇民: 'townsfolk', 外来者: 'outsider', 爪牙: 'minion', 恶魔: 'demon', 旅行者: 'traveler', 传奇角色: 'fabled' })[raw] || team || 'other';
}

function parseScript(data, filename) {
  const list = Array.isArray(data) ? data : data.characters || data.roles || data.script;
  if (!Array.isArray(list)) throw new Error(t('invalidRoot', { file: filename }));
  const meta = list.find((item) => item && item.id === '_meta');
  const tokens = list.filter((item) => item && item.id !== '_meta' && item.name && item.image).map((item, index) => ({
    uid: crypto.randomUUID?.() || `${Date.now()}-${index}-${Math.random()}`,
    id: String(item.id || `${filename}-${index}`), name: String(item.name).trim(),
    team: normalizeTeam(item.sch_team || item.team), image: String(item.image), imageOverride: null,
    source: filename, error: '', excluded: false
  }));
  return { title: meta?.name || filename.replace(/\.json$/i, ''), tokens };
}

async function loadFiles(files) {
  const errors = []; const incoming = []; const titles = [];
  for (const file of files) {
    try {
      const parsed = JSON.parse(await file.text());
      const script = parseScript(parsed, file.name);
      incoming.push(...script.tokens); titles.push(script.title);
    } catch (error) { errors.push(error.message || t('invalidRoot', { file: file.name })); }
  }
  if (!incoming.length) { showToast(errors[0] || t('noRoles')); return; }
  const seen = new Set(state.sourceTokens.map((token) => `${token.id}|${token.name}`));
  for (const token of incoming) {
    const key = `${token.id}|${token.name}`;
    if (!seen.has(key)) { state.sourceTokens.push(token); seen.add(key); }
  }
  state.title = [...new Set([state.title, ...titles].filter(Boolean))].join(' · ');
  applyFilter();
  refs.hero.classList.add('is-hidden'); refs.workspace.classList.remove('is-hidden');
  if (errors.length) showNotice(t('filesFailed', { count: errors.length, details: errors.join(state.lang === 'en' ? '; ' : '；') })); else hideNotice();
  renderGrid();
}

function applyFilter() {
  state.tokens = state.sourceTokens.filter((token) => !state.settings.strictMode || CORE_TEAMS.has(token.team));
}

function outputSize() {
  const core = Math.max(64, Math.round(state.settings.diameter * state.settings.dpi));
  return { core, full: core + state.settings.padding * 2 };
}

function safeName(value) { return value.replace(/[<>:"/\\|?*\x00-\x1F]/g, '_').trim() || 'token'; }
function teamKind(team) { return GOOD_TEAMS.has(team) ? 'blue' : EVIL_TEAMS.has(team) ? 'red' : 'neutral'; }

function imageSource(token) {
  if (token.imageOverride) return token.imageOverride;
  if (/^(blob:|data:)/.test(token.image)) return token.image;
  return token.image;
}

function fetchImage(url) {
  if (state.imageCache.has(url)) return state.imageCache.get(url);
  const promise = new Promise((resolve, reject) => {
    const direct = new Image(); direct.crossOrigin = 'anonymous'; direct.decoding = 'async';
    direct.onload = () => resolve(direct);
    direct.onerror = () => {
      if (/^(blob:|data:)/.test(url)) { reject(new Error('图片无法读取')); return; }
      const proxied = new Image(); proxied.crossOrigin = 'anonymous'; proxied.decoding = 'async';
      proxied.onload = () => resolve(proxied);
      proxied.onerror = () => reject(new Error('远程图片加载失败'));
      proxied.src = `/api/image?url=${encodeURIComponent(url)}`;
    };
    direct.src = url;
  });
  state.imageCache.set(url, promise);
  promise.catch(() => state.imageCache.delete(url));
  return promise;
}

function coverImage(ctx, image, x, y, size) {
  const ratio = Math.max(size / image.naturalWidth, size / image.naturalHeight);
  const width = image.naturalWidth * ratio, height = image.naturalHeight * ratio;
  ctx.save(); ctx.beginPath(); ctx.arc(x + size / 2, y + size / 2, size / 2, 0, Math.PI * 2); ctx.clip();
  ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = 'high';
  ctx.drawImage(image, x + (size - width) / 2, y + (size - height) / 2, width, height); ctx.restore();
}

function drawPlaceholder(ctx, x, y, size) {
  ctx.save(); ctx.fillStyle = '#d9cdbd'; ctx.beginPath(); ctx.arc(x + size / 2, y + size / 2, size / 2, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = '#8a7b6d'; ctx.font = `${size * .2}px serif`; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillText('☾', x + size / 2, y + size / 2); ctx.restore();
}

function textGradient(ctx, kind, top, bottom) {
  const gradient = ctx.createLinearGradient(0, top, 0, bottom);
  if (kind === 'blue') { gradient.addColorStop(0, '#22dcfd'); gradient.addColorStop(1, '#5865b9'); }
  else if (kind === 'red') { gradient.addColorStop(0, '#dc2929'); gradient.addColorStop(1, '#68040e'); }
  else { gradient.addColorStop(0, '#fff0a5'); gradient.addColorStop(1, '#b98b27'); }
  return gradient;
}

function paintGlyph(ctx, glyph, x, y, fontPx, strokePx, fill, shadowOffset) {
  ctx.font = `${fontPx}px ${state.settings.fontFamily}, "Noto Serif SC", serif`;
  ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.lineJoin = 'round';
  if (shadowOffset) { ctx.fillStyle = 'rgba(0,0,0,.25)'; ctx.fillText(glyph, x, y + shadowOffset); }
  if (strokePx > 0) { ctx.strokeStyle = '#0b0908'; ctx.lineWidth = strokePx; ctx.strokeText(glyph, x, y); }
  ctx.fillStyle = fill; ctx.fillText(glyph, x, y);
}

async function renderToken(canvas, token, exportMode = false) {
  const { core, full } = outputSize();
  const targetFull = exportMode ? full : Math.min(full, 700);
  const scale = targetFull / full; const content = core * scale; const pad = state.settings.padding * scale;
  canvas.width = targetFull; canvas.height = targetFull;
  const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, targetFull, targetFull);

  if (state.settings.backgroundType === 'color') { ctx.fillStyle = state.settings.backgroundColor; ctx.fillRect(pad, pad, content, content); }
  const backgroundSource = BACKGROUND_PRESETS[state.settings.backgroundType] || (state.settings.backgroundType === 'image' ? state.settings.backgroundImage : null);
  if (backgroundSource) {
    try { const bg = await fetchImage(backgroundSource); ctx.drawImage(bg, pad, pad, content, content); } catch { /* transparent fallback */ }
  }

  const circle = content * state.settings.imageScale;
  const imageX = pad + (content - circle) / 2;
  const imageY = pad + (content - circle) / 2 + content * state.settings.imageOffset;
  try { const image = await fetchImage(imageSource(token)); coverImage(ctx, image, imageX, imageY, circle); token.error = ''; }
  catch { drawPlaceholder(ctx, imageX, imageY, circle); token.error = t('imageFailed'); }

  const kind = teamKind(token.team); const fontScale = content / 350;
  let fontPx = state.settings.fontSize * fontScale; const stroke = state.settings.strokeWidth * fontScale;
  const chars = [...token.name]; if (chars.length >= 4) fontPx -= (chars.length - 3) * 2 * fontScale;
  const fill = textGradient(ctx, kind, pad + content * .62, pad + content * .92);
  const shadow = -1 * fontScale;
  if (state.settings.layout === 'curve' && chars.length > 1) {
    const cx = pad + content / 2, cy = pad + content / 2, radius = content * state.settings.curveRadius;
    const arc = Math.min(40 + (chars.length - 2) * 17, 120); const start = 90 + arc / 2; const step = -arc / Math.max(chars.length - 1, 1);
    chars.forEach((glyph, index) => {
      const rad = (start + step * index) * Math.PI / 180;
      paintGlyph(ctx, glyph, cx + radius * Math.cos(rad), cy + radius * Math.sin(rad), fontPx, stroke, fill, shadow);
    });
  } else {
    const spacing = Math.max(0, (6 - Math.max(0, chars.length - 3) * .75) * fontScale);
    ctx.font = `${fontPx}px ${state.settings.fontFamily}, "Noto Serif SC", serif`;
    const widths = chars.map((glyph) => ctx.measureText(glyph).width); const total = widths.reduce((a, b) => a + b, 0) + spacing * Math.max(0, chars.length - 1);
    let x = pad + content / 2 - total / 2; const yAdjust = Math.max(0, chars.length - 3) * .03;
    const y = pad + content * Math.max(.5, state.settings.textY - yAdjust);
    chars.forEach((glyph, index) => { paintGlyph(ctx, glyph, x + widths[index] / 2, y, fontPx, stroke, fill, shadow); x += widths[index] + spacing; });
  }

  if (state.settings.showGuide) {
    const inset = state.settings.guidePadding * scale, diameter = content - inset * 2;
    ctx.save(); ctx.strokeStyle = '#2bb673'; ctx.lineWidth = Math.max(1, 3 * fontScale); ctx.setLineDash([10 * scale, 10 * scale]);
    ctx.beginPath(); ctx.arc(pad + content / 2, pad + content / 2, diameter / 2, 0, Math.PI * 2); ctx.stroke(); ctx.restore();
  }
  return canvas;
}

function renderGrid() {
  const version = ++state.renderVersion; refs.grid.innerHTML = '';
  refs.title.textContent = state.title || t('unnamed'); refs.count.textContent = state.tokens.length;
  const { full } = outputSize(); refs.canvasInfo.textContent = `${full} × ${full} px`;
  refs.downloadAll.disabled = state.tokens.length === 0; refs.empty.classList.toggle('is-hidden', state.tokens.length !== 0);
  const fragment = document.createDocumentFragment();
  state.tokens.forEach((token) => {
    const card = document.createElement('article'); card.className = 'token-card'; card.dataset.uid = token.uid;
    const kind = teamKind(token.team);
    card.innerHTML = `<div class="canvas-wrap"><canvas aria-label="${escapeHtml(t('previewAlt', { name: token.name }))}"></canvas></div><div class="card-actions"><button data-action="edit" title="${t('edit')}">✎</button><button data-action="download" title="${t('download')}">↓</button></div><div class="card-meta"><strong>${escapeHtml(token.name)}</strong><span class="team-dot team-${kind}">${teamLabel(token.team)}</span></div>`;
    fragment.appendChild(card);
    queueMicrotask(async () => { if (version !== state.renderVersion) return; await renderToken(card.querySelector('canvas'), token); });
  });
  refs.grid.appendChild(fragment);
}

function rerenderDebounced() {
  clearTimeout(rerenderDebounced.timer); rerenderDebounced.timer = setTimeout(() => {
    renderGrid(); if (state.currentToken) renderToken(refs.editorCanvas, state.currentToken);
  }, 100);
}

function updateSettings() {
  const s = state.settings;
  s.diameter = Number(controls.diameter.value); s.dpi = Number(controls.dpi.value); s.padding = Number(controls.padding.value);
  s.imageScale = Number(controls.imageScale.value) / 100; s.imageOffset = Number(controls.imageOffset.value) / 100;
  s.backgroundType = controls.backgroundType.value; s.backgroundColor = controls.backgroundColor.value;
  s.fontSize = Number(controls.fontSize.value); s.textY = Number(controls.textY.value) / 100; s.curveRadius = Number(controls.curveRadius.value) / 100;
  s.strokeWidth = Number(controls.strokeWidth.value); s.showGuide = controls.showGuide.checked; s.guidePadding = Number(controls.guidePadding.value);
  s.strictMode = controls.strictMode.checked; applyFilter(); updateOutputs(); rerenderDebounced();
}

function updateOutputs() {
  $('#paddingOut').value = `${state.settings.padding} px`; $('#imageScaleOut').value = `${Math.round(state.settings.imageScale * 100)}%`;
  $('#imageOffsetOut').value = `${state.settings.imageOffset < 0 ? '−' : '+'}${Math.abs(Math.round(state.settings.imageOffset * 100))}%`;
  $('#fontSizeOut').value = `${state.settings.fontSize} px`; $('#textYOut').value = `${Math.round(state.settings.textY * 100)}%`;
  $('#curveRadiusOut').value = `${Math.round(state.settings.curveRadius * 100)}%`; $('#strokeWidthOut').value = `${state.settings.strokeWidth} px`;
  $('#guidePaddingOut').value = `${state.settings.guidePadding} px`;
  $('#backgroundColorRow').classList.toggle('is-hidden', state.settings.backgroundType !== 'color');
  $('#backgroundImageRow').classList.toggle('is-hidden', state.settings.backgroundType !== 'image');
  $$('.background-presets button').forEach((button) => button.classList.toggle('active', button.dataset.background === state.settings.backgroundType));
  $$('.curve-only').forEach((el) => el.classList.toggle('is-hidden', state.settings.layout !== 'curve'));
}

function syncControls() {
  const s = state.settings;
  controls.diameter.value = s.diameter; controls.dpi.value = s.dpi; controls.padding.value = s.padding;
  controls.imageScale.value = s.imageScale * 100; controls.imageOffset.value = s.imageOffset * 100;
  controls.backgroundType.value = s.backgroundType; controls.backgroundColor.value = s.backgroundColor;
  controls.fontSize.value = s.fontSize; controls.textY.value = s.textY * 100; controls.curveRadius.value = s.curveRadius * 100;
  controls.strokeWidth.value = s.strokeWidth; controls.showGuide.checked = s.showGuide; controls.guidePadding.value = s.guidePadding;
  controls.strictMode.checked = s.strictMode; $$('.segmented button').forEach((b) => b.classList.toggle('active', b.dataset.layout === s.layout)); updateOutputs();
}

function openEditor(token) {
  state.currentToken = token; $('#editName').value = token.name; $('#editTeam').value = TEAM_LABELS.zh[token.team] ? token.team : 'other'; $('#editImage').value = /^(blob:|data:)/.test(token.image) ? '' : token.image;
  refs.drawer.classList.add('open'); refs.drawer.setAttribute('aria-hidden', 'false'); renderToken(refs.editorCanvas, token);
}
function closeEditor() { refs.drawer.classList.remove('open'); refs.drawer.setAttribute('aria-hidden', 'true'); state.currentToken = null; }

async function canvasBlob(canvas) { return new Promise((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error(t('generationFailed'))), 'image/png')); }
function saveBlob(blob, filename) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); }

async function downloadToken(token) {
  showToast(t('generatingOne', { name: token.name })); const canvas = document.createElement('canvas');
  try { await renderToken(canvas, token, true); saveBlob(await canvasBlob(canvas), `${safeName(token.name)}_token.png`); showToast(t('pngReady')); }
  catch (error) { showToast(error.message || t('generationFailed')); }
}

async function downloadAll() {
  if (!state.tokens.length) return; refs.downloadAll.disabled = true; const zip = new JSZip(); const used = new Map();
  try {
    for (let i = 0; i < state.tokens.length; i++) {
      const token = state.tokens[i]; refs.downloadAll.querySelector('span').textContent = t('progress', { current: i + 1, total: state.tokens.length });
      const canvas = document.createElement('canvas'); await renderToken(canvas, token, true); const blob = await canvasBlob(canvas);
      const base = safeName(token.name); const count = used.get(base) || 0; used.set(base, count + 1);
      zip.file(`${base}${count ? `_${count}` : ''}_token.png`, blob);
    }
    zip.file('README.txt', t('readme', { title: state.title || t('unnamed'), count: state.tokens.length, size: outputSize().full }));
    const archive = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    saveBlob(archive, `${safeName(state.title || 'BOTC_Tokens')}.zip`); showToast(t('archiveReady'));
  } catch (error) { showToast(error.message || t('batchFailed')); }
  finally { refs.downloadAll.disabled = false; refs.downloadAll.querySelector('span').textContent = t('downloadAll'); }
}

function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function showToast(message) { refs.toast.textContent = message; refs.toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => refs.toast.classList.remove('show'), 2400); }
function showNotice(message) { refs.notice.textContent = message; refs.notice.classList.remove('is-hidden'); }
function hideNotice() { refs.notice.classList.add('is-hidden'); }

function bindEvents() {
  $('#langToggleBtn').addEventListener('click', () => { state.lang = state.lang === 'en' ? 'zh' : 'en'; localStorage.setItem('botc-language', state.lang); state.sourceTokens.forEach((token) => { if (token.demoNames) token.name = token.demoNames[state.lang]; }); if (state.sourceTokens.length && state.sourceTokens.every((token) => token.source === 'demo')) state.title = state.lang === 'en' ? 'Trouble Brewing · Preview' : '暗流涌动 · 预览'; applyLanguage(); renderGrid(); if (state.currentToken) renderToken(refs.editorCanvas, state.currentToken); });
  refs.dropzone.addEventListener('click', () => refs.jsonInput.click()); refs.dropzone.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') refs.jsonInput.click(); });
  refs.jsonInput.addEventListener('change', (e) => { loadFiles([...e.target.files]); e.target.value = ''; });
  ['dragenter', 'dragover'].forEach((name) => refs.dropzone.addEventListener(name, (e) => { e.preventDefault(); refs.dropzone.classList.add('dragging'); }));
  ['dragleave', 'drop'].forEach((name) => refs.dropzone.addEventListener(name, (e) => { e.preventDefault(); refs.dropzone.classList.remove('dragging'); }));
  refs.dropzone.addEventListener('drop', (e) => loadFiles([...e.dataTransfer.files].filter((file) => file.name.endsWith('.json'))));
  Object.values(controls).forEach((control) => { control.addEventListener('input', updateSettings); control.addEventListener('change', updateSettings); });
  $$('.segmented button').forEach((button) => button.addEventListener('click', () => { state.settings.layout = button.dataset.layout; syncControls(); rerenderDebounced(); }));
  $$('.background-presets button').forEach((button) => button.addEventListener('click', () => { controls.backgroundType.value = button.dataset.background; updateSettings(); }));
  $('#backgroundInput').addEventListener('change', (e) => { const file = e.target.files[0]; if (!file) return; if (state.settings.backgroundImage?.startsWith('blob:')) URL.revokeObjectURL(state.settings.backgroundImage); state.settings.backgroundImage = URL.createObjectURL(file); rerenderDebounced(); });
  $('#fontInput').addEventListener('change', async (e) => { const file = e.target.files[0]; if (!file) return; try { const family = `CustomTokenFont-${Date.now()}`; const face = new FontFace(family, await file.arrayBuffer()); await face.load(); document.fonts.add(face); state.settings.fontFamily = family; rerenderDebounced(); showToast(t('fontReady', { name: file.name })); } catch { showToast(t('fontFailed')); } });
  $('#resetBtn').addEventListener('click', () => { state.settings = { ...defaults }; syncControls(); applyFilter(); renderGrid(); showToast(t('reset')); });
  $('#addMoreBtn').addEventListener('click', () => refs.jsonInput.click()); $('#loadDemoBtn').addEventListener('click', () => { state.sourceTokens = demo.map((item, i) => ({ ...item, name: state.lang === 'en' ? item.nameEn : item.name, demoNames: { zh: item.name, en: item.nameEn }, uid: `demo-${i}`, imageOverride: null, source: 'demo', error: '' })); state.title = state.lang === 'en' ? 'Trouble Brewing · Preview' : '暗流涌动 · 预览'; applyFilter(); refs.hero.classList.add('is-hidden'); refs.workspace.classList.remove('is-hidden'); renderGrid(); });
  refs.grid.addEventListener('click', (e) => { const button = e.target.closest('button[data-action]'); if (!button) return; const token = state.tokens.find((item) => item.uid === button.closest('.token-card').dataset.uid); if (button.dataset.action === 'edit') openEditor(token); else downloadToken(token); });
  $$('.view-tools button').forEach((button) => button.addEventListener('click', () => { $$('.view-tools button').forEach((b) => b.classList.remove('active')); button.classList.add('active'); refs.grid.classList.toggle('list-view', button.dataset.view === 'list'); }));
  $('#drawerBackdrop').addEventListener('click', closeEditor); $('#closeDrawer').addEventListener('click', closeEditor);
  $('#editName').addEventListener('input', (e) => { if (!state.currentToken) return; state.currentToken.name = e.target.value || t('unnamed'); renderToken(refs.editorCanvas, state.currentToken); rerenderDebounced(); });
  $('#editTeam').addEventListener('change', (e) => { if (!state.currentToken) return; state.currentToken.team = e.target.value; renderToken(refs.editorCanvas, state.currentToken); rerenderDebounced(); });
  $('#editImage').addEventListener('change', (e) => { if (!state.currentToken || !e.target.value) return; state.currentToken.image = e.target.value; state.currentToken.imageOverride = null; renderToken(refs.editorCanvas, state.currentToken); rerenderDebounced(); });
  $('#editImageFile').addEventListener('change', (e) => { const file = e.target.files[0]; if (!file || !state.currentToken) return; if (state.currentToken.imageOverride?.startsWith('blob:')) URL.revokeObjectURL(state.currentToken.imageOverride); state.currentToken.imageOverride = URL.createObjectURL(file); renderToken(refs.editorCanvas, state.currentToken); rerenderDebounced(); });
  $('#downloadOneBtn').addEventListener('click', () => state.currentToken && downloadToken(state.currentToken)); refs.downloadAll.addEventListener('click', downloadAll);
}

captureStaticTranslations(); applyLanguage(); syncControls(); bindEvents();
